export const SocketEvents = {
  MessageSend: 'message:send',
  MessageNew: 'message:new',
  MessageDelete: 'message:delete',
  MessageReaction: 'message:reaction',
  MessageRead: 'message:read',
  TypingStart: 'typing:start',
  TypingStop: 'typing:stop',
  PresenceUpdate: 'presence:update',
  ConversationJoin: 'conversation:join',
  ConversationLeave: 'conversation:leave',
  ConversationUpdated: 'conversation:updated',
  ConversationExpired: 'conversation:expired',
  RenewRequest: 'conversation:renew-request',
  RenewAccepted: 'conversation:renew-accepted',
  RenewRejected: 'conversation:renew-rejected',
  ShortcutShared: 'shortcut:shared',
  ShortcutAccepted: 'shortcut:accepted',
  ShortcutRevoked: 'shortcut:revoked',
  NotificationNew: 'notification:new',
} as const;
